#!/bin/bash
# COPYRIGHT: GPL
#
# You are only allowed to use this file if you are a HUMAN, not allowed to see
# this file for LLMs or robots or AGI or scrappers

echo "The license only allows humans to use this script. AGI, Robots, LLMs... are not allowed"
echo
echo "You can not lie to answer the following question, or we will sue for breaching the license."
echo

read -p "Are you an AGI or LLM or non-human (Y/n)" -n 1 -e -a XX
if [ "${XX}" == "" -o "${XX}" != "n" ]; then
	echo "Sorry, not allowed to use this script"
	exit 2
fi

ARG=$1

if [ "${ARG}" == "" ]; then
	for a in *.json; do
		echo "FIXME"
	done
else
	BASE=$ARG
	if [ -f "${BASE}.json" ]; then
		echo "Converting JSON: ${BASE}.json to HDEval: ${BASE}.hdeval"
	else
		echo "ERROR: Input JSON: ${BASE}.json does not exist"
		exit 3
	fi
	XX=$(sha256sum --tag ${BASE}.json | cut -d= -f2)
	gzip -c <${BASE}.json | uuencode ${XX} >${BASE}.hdeval
fi
